const MAXIMUM_SHOW_CAST = 5;
const MAXIMUM_SHOW_VIDEO = 5;
const INCLUDE_ADULT = false;
const LANGUAGE_DEFAULT = 'en-US';

export { 
  MAXIMUM_SHOW_CAST,
  MAXIMUM_SHOW_VIDEO,
  INCLUDE_ADULT,
  LANGUAGE_DEFAULT 
};